import { existsSync, readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const docsRoot = resolve(process.cwd(), 'public/docs')
const manifest = JSON.parse(
  readFileSync(resolve(process.cwd(), 'docs/site/manifest.json'), 'utf8'),
) as { pages: Array<{ file: string }> }
const pages = manifest.pages.map((page) => page.file)
const generatedNotice = 'Generated by scripts/generate-docs.mjs'

describe('HTML documentation', () => {
  it.each(pages)('%s has a complete document structure', (page) => {
    const source = readFileSync(resolve(docsRoot, page), 'utf8')

    expect(source).toMatch(/^<!doctype html>/i)
    expect(source).toContain('<html lang="zh-CN">')
    expect(source).toContain('name="viewport"')
    expect(source).toMatch(/<title>[^<]+<\/title>/)
    expect(source.match(/<h1(?:\s[^>]*)?>/g)).toHaveLength(1)
    expect(source).toContain(generatedNotice)
    expect(source.endsWith('\n')).toBe(true)
  })

  it('keeps every local document asset and link resolvable', () => {
    for (const page of pages) {
      const pagePath = resolve(docsRoot, page)
      const source = readFileSync(pagePath, 'utf8')
      const references = source.matchAll(/(?:href|src)="([^"]+)"/g)

      for (const [, reference] of references) {
        if (/^(?:https?:|#)/.test(reference)) continue
        const target = reference.split(/[?#]/, 1)[0]
        expect(existsSync(resolve(dirname(pagePath), target)), `${page}: ${reference}`).toBe(
          true,
        )
      }
    }
  })

  it('keeps the edge-case register complete and aligned with API errors', () => {
    const register = readFileSync(resolve(docsRoot, 'edge-cases.html'), 'utf8')
    const source = readFileSync(resolve(process.cwd(), 'server/app.ts'), 'utf8')
    const ids = [...register.matchAll(/<td>((?:B|I|S|R|H|Q)-\d{2})<\/td>/g)].map(
      (match) => match[1],
    )
    const implementedErrors = new Set([
      'INVALID_REQUEST',
      'INTERNAL_ERROR',
      ...[...source.matchAll(/new ApiError\(\s*\d+,\s*'([A-Z_]+)'/g)].map(
        (match) => match[1],
      ),
    ])

    expect(ids).toHaveLength(91)
    expect(new Set(ids).size).toBe(ids.length)
    for (const errorCode of implementedErrors) {
      expect(register, `missing documented error: ${errorCode}`).toContain(
        `<code>${errorCode}</code>`,
      )
    }
    expect(register).toContain('ASSUMPTION')
    expect(register).toContain('OUT OF SCOPE')
    expect(register).toContain('OPEN')
  })
})