import { readFile, mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const sourceRoot = resolve(projectRoot, 'docs/site')
const outputRoot = resolve(projectRoot, 'public/docs')
const checkOnly = process.argv.includes('--check')
const generatedNotice = '<!-- Generated by scripts/generate-docs.mjs. Do not edit this file directly. -->'

const manifest = JSON.parse(
  await readFile(resolve(sourceRoot, 'manifest.json'), 'utf8'),
)

validateManifest(manifest)

const outputs = []
for (const page of manifest.pages) {
  const sourcePath = resolve(sourceRoot, 'pages', page.file)
  const outputPath = resolve(outputRoot, page.file)
  const source = await readFile(sourcePath, 'utf8')
  const rendered = renderPage(source, page.file, manifest)
  outputs.push({ sourcePath, outputPath, rendered })
}

const stylesheetSource = resolve(sourceRoot, 'assets/docs.css')
outputs.push({
  sourcePath: stylesheetSource,
  outputPath: resolve(outputRoot, 'assets/docs.css'),
  rendered: ensureFinalNewline(await readFile(stylesheetSource, 'utf8')),
})

const stale = []
for (const output of outputs) {
  const current = await readFile(output.outputPath, 'utf8').catch(() => null)
  if (current === output.rendered) continue

  if (checkOnly) {
    stale.push(relativePath(output.outputPath))
    continue
  }

  await mkdir(dirname(output.outputPath), { recursive: true })
  await writeFile(output.outputPath, output.rendered, 'utf8')
  console.log(`generated ${relativePath(output.outputPath)}`)
}

if (stale.length > 0) {
  console.error('Generated documentation is stale:')
  for (const path of stale) console.error(`- ${path}`)
  console.error('Run: npm run docs:build')
  process.exitCode = 1
} else if (checkOnly) {
  console.log(`documentation is current (${outputs.length} files)`)
}

function renderPage(source, currentFile, config) {
  if (!/^<!doctype html>/i.test(source)) {
    throw new Error(`${relativePath(resolve(sourceRoot, 'pages', currentFile))}: missing doctype`)
  }
  if ((source.match(/<h1(?:\s[^>]*)?>/g) ?? []).length !== 1) {
    throw new Error(`${currentFile}: expected exactly one h1`)
  }
  if (source.includes(generatedNotice)) {
    throw new Error(`${currentFile}: source template contains generated notice`)
  }

  const navigation = renderNavigation(config.pages, currentFile)
  const withNavigation = source.replace(
    /<nav aria-label="文档导航">[\s\S]*?<\/nav>/,
    navigation,
  )
  if (withNavigation === source) {
    throw new Error(`${currentFile}: document navigation was not found`)
  }

  const replacements = {
    SITE_NAME: config.site.name,
    SITE_VERSION: config.site.version,
    UPDATED_AT: config.site.updatedAt,
    REPOSITORY_URL: config.site.repositoryUrl,
    APPLICATION_URL: config.site.applicationUrl,
  }
  let rendered = withNavigation
  for (const [token, value] of Object.entries(replacements)) {
    rendered = rendered.replaceAll(`{{${token}}}`, escapeHtml(value))
  }

  const unresolved = rendered.match(/{{[A-Z_]+}}/g)
  if (unresolved) {
    throw new Error(`${currentFile}: unresolved tokens ${[...new Set(unresolved)].join(', ')}`)
  }

  return ensureFinalNewline(
    rendered.replace(/^<!doctype html>\s*/i, `<!doctype html>\n${generatedNotice}\n`),
  )
}

function renderNavigation(pages, currentFile) {
  const links = pages.map((page) => {
    const href = page.file === 'index.html' ? './' : `./${page.file}`
    const current = page.file === currentFile ? ' aria-current="page"' : ''
    return `          <a${current} href="${href}">${escapeHtml(page.label)}</a>`
  })

  return [
    '        <nav aria-label="文档导航">',
    '          <span class="nav-label">Documentation</span>',
    ...links,
    '        </nav>',
  ].join('\n')
}

function validateManifest(config) {
  if (!config?.site || !Array.isArray(config.pages) || config.pages.length === 0) {
    throw new Error('docs/site/manifest.json must define site and pages')
  }

  const files = new Set()
  for (const page of config.pages) {
    if (!/^[a-z0-9-]+\.html$/.test(page.file) || !page.label) {
      throw new Error(`invalid page entry: ${JSON.stringify(page)}`)
    }
    if (files.has(page.file)) throw new Error(`duplicate page: ${page.file}`)
    files.add(page.file)
  }
  if (!files.has('index.html')) throw new Error('manifest must include index.html')
}

function ensureFinalNewline(value) {
  return `${value.trimEnd()}\n`
}

function escapeHtml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;')
}

function relativePath(path) {
  return path.replace(`${projectRoot}/`, '')
}